name: aa-tp1
channels:
- anaconda
- conda-forge
- defaults
dependencies:
    - matplotlib
    - seaborn
    - pandas
    - jupyterlab
    - scikit-learn
    - six
    - pydotplus
    - pip
    - pip:
      - imbalanced-learn
